name: Python CI

on:
  push:
    branches: [ main ]
jobs:
  build:
  
    runs-on: self-hosted
        
    steps:
      - uses: actions/checkout@v2
      - name: Move rebuild script
        run: cp ~/rebuild.sh ./rebuild.sh
      - name: Make rebuild script runnable
        run: chmod +x rebuild.sh
      - name: Run rebuild script
        run: ./rebuild.sh
