name: Python CI

on:
  push:
    branches: [ main ]
jobs:
  build:
  
    runs-on: self-hosted
        
    steps:
      - uses: actions/checkout@v4
      - name: Copy files to correct folder
        run: cp ~/actions-runner/_work/DiscordScoresBot/DiscordScoresBot/*.py ~/DiscordScoresBot
      - name: End currently running process
        run: sudo pkill -f main.py
  run:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run new process
        run: nohup python3 ~/DiscordScoresBot/main.py &
