name: Python CI

on:
  push:
    branches: [ main ]
jobs:
  build:
  
    runs-on: self-hosted
        
    steps:
      - uses: actions/checkout@v2
      - name: Move rebuild script
        run: cp ~/rebuild.sh ./rebuild.sh
      - name: Check rebuild script exists
        run: ls -a
