name: Python CI

on:
  push:
    branches: [ main ]
jobs:
  build:
  
    runs-on: self-hosted
        
    steps:
      - uses: actions/checkout@v4
      - name: Copy files to correct folder
        run: cp ~/actions-runner/_work/DiscordScoresBot/DiscordScoresBot/*.py ~/DiscordScoresBot
  run:
    needs: build
    runs-on: self-hosted

    steps:
      - shell: bash
        run: ~/DiscordScoresBot/rebuild.sh
