name: Main Workflow

on:
  push:
    branches: [main]

jobs:
  clone:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Copy Python files to correct folder
        run: cp ~/actions-runner/_work/DiscordScoresBot/DiscordScoresBot/*.py ~/DiscordScoresBot

      - name: Copy Dockerfile to correct folder
        run: cp ~/actions-runner/_work/DiscordScoresBot/DiscordScoresBot/Dockerfile ~/DiscordScoresBot

      - name: Start Docker
        run: sudo systemctl start docker

  destroy:
    needs: clone
    runs-on: self-hosted

    steps:
      - name: Prune deprecated docker data
        run: sudo docker system prune -f

      - name: Stop current container
        run: sudo docker stop discord-scores-bot

      - name: Remove current container
        run: sudo docker rm discord-scores-bot

  build:
    needs: destroy
    runs-on: self-hosted

    steps:
      - name: Build new container
        run: sudo docker build -t discord-scores-bot ~/DiscordScoresBot

  run:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run new container
        run: sudo docker run -d --name discord-scores-bot discord-scores-bot
